server:
  host: "0.0.0.0"
  port: 42000
  timeout: "5m"
  max_connections: 200
  name: "YSF Nexus"
  description: "Go YSF Reflector"

web:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  auth_required: false  # Set to true to protect settings with authentication
  username: "admin"     # Required if auth_required is true
  password: "changeme"  # Required if auth_required is true - CHANGE THIS!

bridges:
  # YSF Bridge to external YSF reflector
  - name: "YSF001"
    type: ysf                # Bridge type: "ysf" or "dmr"
    host: "ysf001.example.com"
    port: 42000
    schedule: "0 */6 * * *"  # Every 6 hours
    duration: "1h"
    enabled: false

  # YSF Bridge for weekly net
  - name: "Regional Net"
    type: ysf
    host: "regional.ysf.net"
    port: 42000
    schedule: "0 20 * * 6"   # Saturdays at 8 PM
    duration: "1h30m"        # 1.5 hours
    enabled: false

  # DMR Bridge to BrandMeister
  - name: "BrandMeister TG91"
    type: dmr
    schedule: "0 20 * * 0"   # Sundays at 8 PM
    duration: "2h"
    enabled: false
    dmr:
      id: 1234567            # Your DMR ID (7-digit number)
      network: "BrandMeister"
      address: "3100.r2.bm.dmrlog.net"
      port: 62031
      callsign: "MYHOTSPT"     # Optional: callsign to send in RPTC (defaults to bridge name)
  password: "passw0rd"   # CHANGE THIS! You can also set this via env var BRIDGE_BRANDMEISTERTG91_DMR_PASSWORD
      talk_group: 91         # Worldwide
      slot: 2
      color_code: 1
      # Optional repeater info
      rx_freq: 435000000
      tx_freq: 435000000
      tx_power: 25           # TX power in dBm (00-99), 25 dBm ≈ 316 watts
      latitude: 42.5803
      longitude: -82.9469
      height: 50
      location: "Macomb, MI"
      description: "YSF Nexus DMR Bridge"
      url: "https://example.com"
      ping_interval: "10s"
      auth_timeout: "30s"

  # Permanent DMR Bridge (always connected)
  - name: "BrandMeister TAC310"
    type: dmr
    permanent: true          # Always stay connected
    enabled: false
    dmr:
      id: 1234567
      network: "BrandMeister"
      address: "3100.r2.bm.dmrlog.net"
      port: 62031
     callsign: "TAC310"     # Optional: callsign to send in RPTC
     password: "passw0rd"   # Or set via BRIDGE_BRANDMEISTERTAC310_DMR_PASSWORD
      talk_group: 310        # TAC 310
      slot: 2
      color_code: 1

mqtt:
  enabled: false
  broker: "tcp://localhost:1883"
  topic_prefix: "ysf/reflector"
  client_id: "ysf-nexus"
  username: ""
  password: ""
  qos: 1
  retained: false

blocklist:
  enabled: true
  callsigns: []
  # - "BLOCKED"
  # - "SPAM123"

logging:
  level: "info"        # debug, info, warn, error
  format: "text"       # text, json
  file: ""             # empty for stdout only
  max_size: 100        # MB
  max_backups: 3
  max_age: 28         # days

metrics:
  enabled: true
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"

# YSF2DMR Bridge - Enables cross-mode YSF ↔ DMR voice bridging
ysf2dmr:
  enabled: false  # Set to true to enable YSF2DMR bridge

  # YSF side configuration
  ysf:
    callsign: "YSF2DMR"
    suffix: "ND"               # Optional suffix for WiresX
    local_address: "0.0.0.0"   # Address to bind YSF listener
    local_port: 42001          # Port for YSF repeaters to connect
    enable_wiresx: false       # Enable WiresX protocol support
    hang_time: "5s"            # Time to keep stream open after last packet

  # DMR network configuration
  dmr:
    enabled: true
    id: 1234567                # Your DMR ID (7-digit number)
    network: "BrandMeister"    # Network name (for display)
    address: "3100.r2.bm.dmrlog.net"  # DMR network server address
    port: 62031                # DMR network port
  password: "passw0rd"       # Network password - CHANGE THIS! You can also set global env var YSF2DMR_DMR_PASSWORD
    startup_tg: 91             # Default talk group (91 = Worldwide)
    slot: 2                    # DMR slot (1 or 2, usually 2)
    color_code: 1              # Color code (usually 1)
    enable_private_call: false # Enable DMR private calls

    # Optional repeater info for networks that require it
    rx_freq: 435000000         # RX frequency in Hz (435.000 MHz)
    tx_freq: 435000000         # TX frequency in Hz
    tx_power: 25               # TX power in dBm (00-99), 25 dBm ≈ 316 watts
    latitude: 42.5803          # Repeater latitude
    longitude: -82.9469        # Repeater longitude
    height: 50                 # Height above ground in meters
    location: "Macomb, MI"     # Location description
    description: "YSF2DMR Bridge"
    url: "https://example.com"

    ping_interval: "10s"       # Keep-alive ping interval
    auth_timeout: "30s"        # Authentication timeout

  # DMR ID lookup configuration
  lookup:
    enabled: true
    dmr_id_file: "dmr_ids.csv"           # Path to DMR ID database file
    auto_download: false                 # Auto-download database from RadioID.net
    download_url: "https://radioid.net/static/users.csv"
    refresh_interval: "24h"              # How often to refresh database

  # Audio conversion settings
  audio:
    gain: 1.0                  # Audio gain multiplier (0.1 to 5.0)
    vox_enabled: false         # Enable VOX (voice-activated transmission)
    vox_threshold: 0.1         # VOX threshold (0.0 to 1.0)