name: Dagger CI

on:
  push:
    branches: [ main, 'pr/*', 'fix/*', 'pr/fix/*', 'pr/fix/openspot-status-response-clean' ]
  pull_request:
    branches: [ main ]

jobs:
  dagger:
    name: Run Dagger CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install Dagger CLI
        run: |
          echo "Installing Dagger CLI"
          DAGGER_VERSION="v0.18.19"
          # Download from GitHub releases (more secure than install script)
          curl -fsSL "https://github.com/dagger/dagger/releases/download/${DAGGER_VERSION}/dagger_${DAGGER_VERSION}_linux_amd64.tar.gz" -o dagger.tar.gz
          # Verify it's a valid tar.gz file
          file dagger.tar.gz | grep -q "gzip compressed data"
          tar -xzf dagger.tar.gz dagger
          chmod +x dagger
          sudo mv dagger /usr/local/bin/dagger
          dagger version

      - name: Run Dagger CI Pipeline
        run: |
          dagger call ci --source=.
