name: Dagger CI

on:
  push:
    branches: [ main, 'pr/*', 'fix/*', 'pr/fix/*', 'pr/fix/openspot-status-response-clean' ]
  pull_request:
    branches: [ main ]

jobs:
  dagger:
    name: Run Dagger CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install Dagger CLI (official installer)
        run: |
          echo "Installing Dagger CLI using official installer"
          DAGGER_VERSION="v0.18.19"
          # Download the official installer from dl.dagger.io and run it.
          # The installer handles arch detection and checksum verification.
          curl -fsSL https://dl.dagger.io/dagger/install.sh -o /tmp/install-dagger.sh
          chmod +x /tmp/install-dagger.sh
          # Run the installer with BIN_DIR=/usr/local/bin. Use sudo if needed.
          sudo env BIN_DIR=/usr/local/bin DAGGER_VERSION=${DAGGER_VERSION} /bin/sh /tmp/install-dagger.sh
          rm -f /tmp/install-dagger.sh
          dagger version

      - name: Dagger smoke test
        run: |
          echo "Running Dagger smoke tests"
          # Show installed binary and check architecture
          file $(which dagger) || true
          dagger version
          # Basic CLI sanity checks
          dagger help >/dev/null
          # Try a minimal invocation of the local module; this should return non-error quickly
          # If the module isn't available, this will still validate the CLI runtime
          dagger --version >/dev/null

      - name: Run Dagger CI Pipeline
        run: |
          dagger call ci --source=.
