name: golangci-lint

on:
  push:
    branches: [ main, 'pr/*', 'fix/*', 'pr/fix/*', 'pr/fix/openspot-status-response-clean' ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install golangci-lint (build from source with go install)
        run: |
          # Build golangci-lint with the runner's Go toolchain to avoid
          # mismatches between the binary's build Go version and the
          # repository's targeted Go version. Install into GOPATH/bin and
          # copy to /usr/local/bin so the binary is available to subsequent
          # steps without requiring step-local PATH changes.
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          LINT_BIN="$(go env GOPATH)/bin/golangci-lint"
          echo "built: $LINT_BIN"
          if [ -f "$LINT_BIN" ]; then
            sudo cp "$LINT_BIN" /usr/local/bin/
            sudo chmod +x /usr/local/bin/golangci-lint
          else
            echo "golangci-lint binary not found at $LINT_BIN" >&2
            exit 1
          fi
          /usr/local/bin/golangci-lint --version

      - name: Run golangci-lint
        run: |
          golangci-lint --version
          golangci-lint run ./...
