name: golangci-lint

on:
  push:
    branches: [ main, 'pr/*', 'fix/*', 'pr/fix/*', 'pr/fix/openspot-status-response-clean' ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install golangci-lint v2 (build with runner Go)
        run: |
          # Build the v2 golangci-lint binary with the runner's Go to ensure the
          # tool is built with Go >= the targeted Go version used in the repo.
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v2.0.0
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: |
          golangci-lint --version
          golangci-lint run ./...
