name: golangci-lint

on:
  workflow_dispatch: {}

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install dev tools and run linter via Makefile
        run: |
          # Use the project's Makefile to install and run dev tools. This
          # centralizes tooling and keeps CI consistent with local dev.
          make install-tools
          make lint
