name: golangci-lint

on:
  push:
    branches: [ main, 'pr/*', 'fix/*', 'pr/fix/*', 'pr/fix/openspot-status-response-clean' ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install golangci-lint (build from source with go install)
        run: |
          # Build golangci-lint with the runner's Go toolchain to avoid
          # mismatches between the binary's build Go version and the
          # repository's targeted Go version. Using the module path lets
          # `go install ...@latest` resolve v2 when it exists.
          export GOBIN="$RUNNER_TEMP/gobin"
          mkdir -p "$GOBIN"
          export PATH="$GOBIN:$PATH"
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint --version

      - name: Run golangci-lint
        run: |
          golangci-lint --version
          golangci-lint run ./...
