name: golangci-lint

on:
  push:
    branches: [ main, 'pr/*', 'fix/*', 'pr/fix/*', 'pr/fix/openspot-status-response-clean' ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install golangci-lint v2
        run: |
          # golangci-lint v2 installer is available under the v2 release tag
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v2/install.sh | sh -s -- -b $GITHUB_WORKSPACE/.bin v2.0.0
          echo "$GITHUB_WORKSPACE/.bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: |
          golangci-lint --version
          golangci-lint run ./...
