name: golangci-lint

on:
  push:
    branches: [ main, 'pr/*', 'fix/*', 'pr/fix/*', 'pr/fix/openspot-status-response-clean' ]
  pull_request:
    branches: [ main ]

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install golangci-lint v2 (download release)
        run: |
          mkdir -p $GITHUB_WORKSPACE/.bin
          curl -sSL https://github.com/golangci/golangci-lint/releases/download/v2.0.0/golangci-lint-2.0.0-linux-amd64.tar.gz -o /tmp/golangci-lint.tar.gz
          tar -xzf /tmp/golangci-lint.tar.gz -C /tmp
          mv /tmp/golangci-lint-2.0.0-linux-amd64/golangci-lint $GITHUB_WORKSPACE/.bin/
          echo "$GITHUB_WORKSPACE/.bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: |
          golangci-lint --version
          golangci-lint run ./...
