name: govulncheck

on:
  push:
    branches: [ main, 'pr/*', 'fix/*', 'pr/fix/*', 'pr/fix/openspot-status-response-clean' ]
  pull_request:
    branches: [ main ]

jobs:
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install govulncheck
        run: |
          echo "Installing govulncheck@latest"
          export GOBIN="$RUNNER_TEMP/gobin"
          mkdir -p "$GOBIN"
          export PATH="$GOBIN:$PATH"
          go install golang.org/x/vuln/cmd/govulncheck@latest
          GOV_BIN="$GOBIN/govulncheck"
          echo "built: $GOV_BIN"
          if [ ! -f "$GOV_BIN" ]; then
            echo "govulncheck binary not found at $GOV_BIN" >&2
            exit 1
          fi
          echo "$GOBIN" >> "$GITHUB_PATH"
          govulncheck -v || true

      - name: Run govulncheck
        run: |
          # Run from the module root where go.mod exists
          cd ysf-nexus
          # Fail the job if govulncheck finds vulnerabilities (it exits non-zero)
          govulncheck ./...
