name: govulncheck

on:
  workflow_dispatch: {}

jobs:
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install dev tools and run govulncheck
        run: |
          make install-tools
          # Locate the module root (where go.mod lives). The repository layout
          # may place the module at the repo root or in a subdirectory named
          # `ysf-nexus` (or other). Detect it robustly and cd there.
          if [ -f go.mod ]; then
            MODROOT=.
          elif [ -f ysf-nexus/go.mod ]; then
            MODROOT=ysf-nexus
          else
            MODPATH=$(git ls-files | grep -m1 '^.*/go.mod' || true)
            if [ -n "$MODPATH" ]; then
              MODROOT=$(dirname "$MODPATH")
            else
              echo "could not find go.mod in repository" >&2
              exit 1
            fi
          fi
          echo "module root=$MODROOT"
          cd "$MODROOT"
          # Fail the job if govulncheck finds vulnerabilities (it exits non-zero)
          govulncheck ./...
